---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['KITCHEN_SSH_KEY_NAME'] || "key_Sandbox" %>
  region: us-west-2
  security_group_ids: sg-0d17c079f6f016541
  instance_type: t2.micro
  associate_public_ip: true
  shared_credentials_profile: sandbox

provisioner:
  name: puppet_apply
  manifests_path: /var/lib/jenkins/workspace/Development/Deploy_tomcat_puppet_module/manifests
  modules_path: /var/lib/jenkins/workspace/Development/Deploy_tomcat_puppet_module

platforms:
  - name: centos-7
    driver:
      image_id: "ami-0376dd8c30a3fe7a9"


suites:
  - name: default
    run_list:
    attributes:
